name: PocketRegion
main: PocketRegion\PocketRegion
author: Dutok
api: [1.1.0]
version: 0.1
commands:
  define:
    description: Defines the region.
    permissions: pocketregion.create
    usage: /define <distance> <name>